---
# Source: sonarqube-dce/templates/init-fs.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-sonarqube-dce-init-fs
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2026.3.1
    release: sonarqube
    heritage: Helm
data:
  init_fs.sh: |-
    chown -R 1000:0 /opt/sonarqube/data
    chown -R 1000:0 /opt/sonarqube/temp
    chown -R 1000:0 /opt/sonarqube/logs
