---
# Source: sonarqube-dce/templates/jdbc-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-sonarqube-dce-jdbc-config
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2026.3.1
    release: sonarqube
    heritage: Helm
data:
  SONAR_JDBC_USERNAME: "sonar"
  SONAR_JDBC_URL: "jdbc:postgresql://postgres-postgresql.sonarqube-dce.svc.cluster.local:5432/sonar"

