---
# Source: sonarqube-dce/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-sonarqube-dce-monitoring-passcode
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2026.3.1
    release: sonarqube
    heritage: Helm
type: Opaque
data:
  SONAR_WEB_SYSTEMPASSCODE: "Z2l0b3BzLWRlbW8tcGFzc2NvZGU="
---
# Source: sonarqube-dce/templates/secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-sonarqube-dce-jwt
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2026.3.1
    release: sonarqube
    heritage: Helm
type: Opaque
data:
  SONAR_AUTH_JWTBASE64HS256SECRET: "aFcreTRraXdIUUpSUmFyUWsrdzAwOTVsak1oWXFQV09CNmhUcmxjWjNlYTJOOGJMeGR6clVoSFpIdTliaFJWVnBSMWhBdjhXNFloRGdCeWN2V2x4UUE9PQ=="
---
# Source: sonarqube-dce/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-sonarqube-dce-admin-password
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2026.3.1
    release: sonarqube
    heritage: Helm
type: Opaque
stringData:
  password: "AdminAdmin_12$"
  currentPassword:
---
# Source: sonarqube-dce/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-sonarqube-dce-http-proxies
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2026.3.1
    release: sonarqube
    heritage: Helm
type: Opaque
stringData:
  PLUGINS-HTTP-PROXY: ""
  PLUGINS-HTTPS-PROXY: ""
  PLUGINS-NO-PROXY: ""
  PROMETHEUS-EXPORTER-HTTP-PROXY: ""
  PROMETHEUS-EXPORTER-HTTPS-PROXY: ""
  PROMETHEUS-EXPORTER-NO-PROXY: ""
