---
# Source: sonarqube-dce/templates/sonarqube-application.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-sonarqube-dce-app
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2026.3.1
    release: sonarqube
    heritage: Helm
    app.kubernetes.io/name: sonarqube
    sonarqube.datacenter/type: "app"
    app.kubernetes.io/instance: sonarqube
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: sonarqube
    app.kubernetes.io/component: sonarqube-sonarqube-dce
    app.kubernetes.io/version: "2026.3.1-datacenter-app"
spec:
  replicas: 2
  revisionHistoryLimit: 
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarqube-dce
      release: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube-dce
        release: sonarqube
        sonarqube.datacenter/type: "app"
      annotations:
        checksum/plugins: 3331df20889247d5a9ac9e016b5a765074c43c6096ae2876af26b8a8f91c8e43
        checksum/config: 05542096c345d3ada0b1505108be37db95a62a7bb24efe5e07ee82a8cb73cb6c
        checksum/secret: be831a29556a1e77c556d3a1e683b63f1a7096a67169bf43e828b1b0cbdcb101
    spec:
      automountServiceAccountToken: false
      initContainers:
        - command:
          - sh
          - -c
          - |
            echo "Waiting for headless service DNS to resolve..."
            until nslookup sonarqube-sonarqube-dce-headless; do
              echo "Not yet, retrying in 3s..."
              sleep 3
            done
            echo "DNS ready. Sleeping 5s to ensure propagation..."
            sleep 5
          image: busybox:1.28
          name: wait-for-headless-dns
      securityContext:
        fsGroup: 0
      containers:
        - name: sonarqube-dce
          image: sonarqube:2026.3.1-datacenter-app
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: hazelcast
              containerPort: 9003
              protocol: TCP
          resources:
            limits:
              cpu: 800m
              ephemeral-storage: 512000M
              memory: 4096M
            requests:
              cpu: 400m
              ephemeral-storage: 1536M
              memory: 4096M
          env:
            - name: SONAR_WEB_CONTEXT
              value: /
            - name: SONAR_WEB_JAVAOPTS
              value: ""
            - name: SONAR_CE_JAVAOPTS
              value: ""
            - name: SONAR_LOG_JSONOUTPUT
              value: "false"
            - name: SONAR_HELM_CHART_VERSION
              value: 2026.3.1
            - name: SONAR_CLUSTER_SEARCH_HOSTS
              value: "sonarqube-sonarqube-dce-search"
            - name: SONAR_CLUSTER_KUBERNETES
              value: "true"
            - name: SONAR_CLUSTER_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SONAR_CLUSTER_HOSTS
              value: "sonarqube-sonarqube-dce-headless"
            - name: SONAR_AUTH_JWTBASE64HS256SECRET
              valueFrom:
                secretKeyRef:
                  name: "sonarqube-sonarqube-dce-jwt"
                  key: SONAR_AUTH_JWTBASE64HS256SECRET
            - name: SONAR_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sonarqube-db-secret
                  key: password
            - name: SONAR_WEB_SYSTEMPASSCODE
              valueFrom:
                secretKeyRef:
                  name: sonarqube-sonarqube-dce-monitoring-passcode
                  key: SONAR_WEB_SYSTEMPASSCODE
          envFrom:
            - configMapRef:
                name: sonarqube-sonarqube-dce-jdbc-config
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - |-
                host="$(hostname -i || echo '127.0.0.1')"
                curl --noproxy "*" -fsS -o /dev/null --max-time 1 -H "X-Sonar-Passcode: $SONAR_WEB_SYSTEMPASSCODE" "http://${host}:9000/api/system/liveness"
            failureThreshold: 6
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - |-
                #!/bin/bash
                # A Sonarqube container is considered ready if the status is UP, DB_MIGRATION_NEEDED or DB_MIGRATION_RUNNING
                # status about migration are added to prevent the node to be kill while sonarqube is upgrading the database.
                host="$(hostname -i || echo '127.0.0.1')"
                if curl --noproxy "*" -s http://${host}:9000/api/system/status | grep -q -e '"status":"UP"' -e '"status":"DB_MIGRATION_NEEDED"' -e '"status":"DB_MIGRATION_RUNNING"'; then
                  exit 0
                fi
                exit 1
            failureThreshold: 8
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 1
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /api/system/status
              port: http
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 32
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsGroup: 0
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /opt/sonarqube/data
              name: sonarqube
              subPath: data
            - mountPath: /opt/sonarqube/temp
              name: sonarqube
              subPath: temp
            - mountPath: /opt/sonarqube/logs
              name: sonarqube
              subPath: logs
            - mountPath: /tmp
              name: tmp-dir
      serviceAccountName: default
      volumes:
      
      - name: install-plugins
        configMap:
          name: sonarqube-sonarqube-dce-install-plugins
          items:
            - key: install_plugins.sh
              path: install_plugins.sh
      - name: sonarqube
        emptyDir:
          {}
      - name : tmp-dir
        emptyDir:
          {}

